---
- name: Add friendica configuration (.htconfig.php)
  template:
    src: ".htconfig.php.j2"
    dest: "{{ friendica_path }}/.htconfig.php"
    owner: "{{ friendica_user }}"
    group: "{{ friendica_group }}"
    mode: 0644

- name: Add friendica configuration (local.ini.php)
  template:
    src: "local.ini.php.j2"
    dest: "{{ friendica_path }}/config/local.ini.php"
    owner: "{{ friendica_user }}"
    group: "{{ friendica_group }}"
    mode: 0644

- name: Remove .htconfig.php (Develop)
  file:
    state: absent
    dest: "{{ friendica_path }}/.htconfig.php"
  when: friendica_branch == 'develop' 

- name: Create apache VirtualHost configuration
  template:
    src: "vhost.conf.j2"
    dest: "{{ apache_conf_path }}/sites-available/friendica.conf"
    owner: "{{ friendica_user }}"
    group: "{{ friendica_group }}"
    mode: 0644
  notify: restart apache
  when: friendica_vhost_servername is defined

- name: Enable friendica VirtualHost configuration
  file:
    src: "{{ apache_conf_path }}/sites-available/friendica.conf"
    dest: "{{ apache_conf_path }}/sites-enabled/friendica.conf"
    state: link
  notify: restart apache
  when: friendica_vhost_servername is defined
