---
- name: Install friendica dependencies
  command: "/usr/bin/php bin/composer.phar install"
  args:
    chdir: "{{ friendica_path }}"

- name: Create worker cronjob
  cron:
    name: "Friendica worker"
    minute: "*/10"
    job: "(cd {{ friendica_path }}; /usr/bin/php bin/worker.php) 2>&1 > /dev/null"
    user: "{{ friendica_user }}"
  when: friendica_config_system_pidfile == '' 

- name: Upload update script
  copy:
    src: "{{ role_path }}/files/update.sh"
    dest: /usr/local/bin/friendica-update
    mode: 0755

- name: Create git pull cronjob
  cron:
    name: "update Friendica"
    special_time: "{{ friendica_pull_cron }}"
    value: "/bin/bash /usr/local/bin/friendica-update \"{{ friendica_path }}\" 2>&1 > /dev/null"
    user: "{{ friendica_user }}"
  when: friendica_pull_cron is defined

- name: Create daemon service
  template:
    src: "friendica-daemon.service.j2"
    dest: "/lib/systemd/system/friendica-daemon.service"
    owner: "root"
    group: "root"
    mode: 0644
  when: friendica_config_system_pidfile != ''

- name: Enable and start the friendica daemon
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: friendica-daemon
  when: friendica_config_system_pidfile != ''