---
- name: Install friendica dependencies
  command: "/usr/bin/php bin/composer.phar install"
  args:
    chdir: "{{ friendica_path }}"
  when: friendica_branch == 'develop'

- name: Create worker cronjob
  cron:
    name: "Friendica worker"
    minute: "*/10"
    job: "(cd {{ friendica_path }}; /usr/bin/php bin/worker.php) 2>&1 > /dev/null"
    user: "{{ friendica_user }}"
  when: friendica_branch == 'develop'

- name: Create git pull cronjob
  cron:
    name: "update Friendica"
    special_time: "{{ friendica_pull_cron }}"
    value: "(cd {{ friendica_path }}; git pull) 2>&1 > /dev/null"
    user: "{{ friendica_user }}"
  when: friendica_pull_cron is defined